github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.JAVA_GITHUB_TOKEN }}

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/java-buildpacks"

package:
  repository:     gcr.io/paketo-buildpacks/alibaba-dragonwell
  register:       true
  registry_token: ${{ secrets.JAVA_GITHUB_TOKEN }}

docker_credentials:
- registry: gcr.io
  username: _json_key
  password: ${{ secrets.JAVA_GCLOUD_SERVICE_ACCOUNT_KEY }}

dependencies:
- name:            JDK 8
  id:              jdk
  version_pattern: "8\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/alibaba-dragonwell-dependency:main
  with:
    glob:       Alibaba_Dragonwell_[\d\.]+_x64_linux.tar.gz$
    repository: dragonwell8
    token:      ${{ secrets.JAVA_GITHUB_TOKEN }}
- name:            JDK 11
  id:              jdk
  version_pattern: "11\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/alibaba-dragonwell-dependency:main
  with:
    glob:       Alibaba_Dragonwell_[\d\.]+_x64_linux.tar.gz$
    repository: dragonwell11
    token:      ${{ secrets.JAVA_GITHUB_TOKEN }}
- name:            JDK 17
  id:              jdk
  version_pattern: "17\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/alibaba-dragonwell-dependency:main
  with:
    glob:       Alibaba_Dragonwell_[\d\.]+_x64_linux.tar.gz$
    repository: dragonwell17
    token:      ${{ secrets.JAVA_GITHUB_TOKEN }}
